{% set name = "Flask-Security-Too" %}
{% set version = "5.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62b19397e8d71a8d4cb8dc0d4409cc7a1497982549030396960aee518755e583

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - importlib-resources >=5.10.0
    - python >=3.8
    - flask >=2.3.2
    - flask-login >=0.6.2
    - flask-principal >=0.4.0
    - flask-wtf >=1.1.2
    - email-validator >=2.0.0
    - markupsafe >=2.1.0
    - passlib >=1.7.4
    - wtforms >=3.0.0
    - importlib_resources >=5.10.0

test:
  imports:
    - flask_security
    - flask_security.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Flask-Middleware/flask-security
  summary: Simple security for Flask apps.
  license: MIT
  license_file: LICENSE
  doc_url: https://flask-security-too.readthedocs.io/

extra:
  recipe-maintainers:
    - synapticarbors
