{% set name = "Flask-Security-Too" %}
{% set version = "3.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c52b0e0c8453a012122aad102041fd71bd1ea025f5154bbfb1d20b4c6a4477e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - babel >=1.3
    - pip
    - pytest-runner >=2.6.2
    - python >=3.6
    - twine
    - wheel
  run:
    - python >=3.6
    - email-validator >=1.0.5
    - flask >=1.0.2
    - flask-babelex >=0.9.3
    - flask-login >=0.4.1
    - flask-mail >=0.9.1
    - flask-principal >=0.4.0
    - flask-wtf >=0.14.2
    - itsdangerous >=1.1.0
    - passlib >=1.7.1

test:
  imports:
    - flask_security
    - flask_security.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Flask-Middleware/flask-security
  summary: Simple security for Flask apps.
  license: MIT
  license_file: LICENSE
  doc_url: https://flask-security-too.readthedocs.io/

extra:
  recipe-maintainers:
    - synapticarbors
