{% set name = "Flask-Security-Too" %}
{% set version = "5.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2d1abd2b6b20a90aa7b966561982aef3bbbef20313b0d7d8e7c39e8fe5c5c34

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - flask >=2.3
    - flask-login >=0.6.2
    - flask-principal >=0.4.0
    - flask-wtf >=1.1.1
    - email-validator >=1.1.1
    - passlib >=1.7.4
    - wtforms >=3.0.0
    - importlib_resources>=5.10.0

test:
  imports:
    - flask_security
    - flask_security.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Flask-Middleware/flask-security
  summary: Simple security for Flask apps.
  license: MIT
  license_file: LICENSE
  doc_url: https://flask-security-too.readthedocs.io/

extra:
  recipe-maintainers:
    - synapticarbors
