{% set name = "Flask-Security-Too" %}
{% set version = "4.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4aa0a076fe0faabf01017d727e81fce0800170ce1cbf01534d16549fa6464d87

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - email-validator >=1.1.1
    - flask >=1.1.1
    - flask-login >=0.4.1
    - flask-principal >=0.4.0
    - flask-wtf >=0.14.3
    - itsdangerous >=1.1.0
    - passlib >=1.7.2

test:
  imports:
    - flask_security
    - flask_security.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Flask-Middleware/flask-security
  summary: Simple security for Flask apps.
  license: MIT
  license_file: LICENSE
  doc_url: https://flask-security-too.readthedocs.io/

extra:
  recipe-maintainers:
    - synapticarbors
