context:
  version: "5.8.1"

package:
  name: flask-security-too
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/flask-security-too/flask_security_too-${{ version }}.tar.gz
  sha256: 19450675a19055a3229b9ba5447491fa1233b41c0edf4917ea970222a15fc09e
  patches:
    - rename-pyproject-toml.patch

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - flit-core >=3.8,<4
  run:
    - python >=${{ python_min }}
    - flask >=3.1.1
    - flask-login >=0.6.3
    - flask-principal >=0.4.0
    - flask-wtf >=1.1.2
    - email-validator >=2.3.0
    - markupsafe >=2.1.0
    - libpass >=1.9.3
    - wtforms >=3.0.0

tests:
  - python:
      imports:
        - flask_security
        - flask_security.models
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - python -c "import flask_security"
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Simple security for Flask apps.
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/pallets-eco/flask-security
  documentation: https://flask-security.readthedocs.io/

extra:
  recipe-maintainers:
    - synapticarbors
